-- Create all silver tables if they do not yet exist.
-- Run this before any MERGE statements.

CREATE TABLE IF NOT EXISTS `{{ var.value.gcp_project_id }}.silver.respiratory_virus` (
  season                STRING,
  age_group             STRING,
  rpho_region           STRING,
  week_ending           DATE,
  mmwr_week             INT64,
  mmwr_year             INT64,
  cov_positives         INT64,
  cov_total_tests       INT64,
  cov_tp                FLOAT64,
  cov_tp_level          STRING,
  cov_ed_visits         INT64,
  cov_adm               INT64,
  cov_adm_rate          FLOAT64,
  cov_adm_level         STRING,
  cov_deaths            INT64,
  cov_deaths_per        FLOAT64,
  flu_positives         INT64,
  flu_total_tests       INT64,
  flu_tp                FLOAT64,
  flu_tp_level          STRING,
  flu_a_tests           INT64,
  flu_b_tests           INT64,
  flu_ed_visits         INT64,
  flu_adm               INT64,
  flu_adm_rate          FLOAT64,
  flu_adm_level         STRING,
  flu_deaths            INT64,
  flu_deaths_per        FLOAT64,
  rsv_positives         INT64,
  rsv_total_tests       INT64,
  rsv_tp                FLOAT64,
  rsv_tp_level          STRING,
  rsv_ed_visits         INT64,
  rsv_adm               INT64,
  rsv_adm_rate          FLOAT64,
  rsv_adm_level         STRING,
  rsv_deaths            INT64,
  rsv_deaths_per        FLOAT64,
  total_deaths          INT64,
  population            INT64,
  season_cov_ped_deaths INT64,
  season_flu_ped_deaths INT64,
  season_rsv_ped_deaths INT64,
  _ingestion_timestamp  STRING,
  _batch_id             STRING
);

CREATE TABLE IF NOT EXISTS `{{ var.value.gcp_project_id }}.silver.covid_vaccines_by_county` (
  county                       STRING,
  administered_date            TIMESTAMP,
  total_doses                  INT64,
  cumulative_total_doses       INT64,
  partially_vaccinated         INT64,
  total_partially_vaccinated   INT64,
  fully_vaccinated             INT64,
  cumulative_fully_vaccinated  INT64,
  at_least_one_dose            INT64,
  cumulative_at_least_one_dose INT64,
  california_flag              BOOL,
  up_to_date_count             INT64,
  cumulative_up_to_date_count  INT64,
  _ingestion_timestamp         STRING,
  _batch_id                    STRING
);

CREATE TABLE IF NOT EXISTS `{{ var.value.gcp_project_id }}.silver.cms_revoked_medicare_providers` (
  enrlmt_id                    STRING,
  npi                          STRING,
  first_name                   STRING,
  middle_name                  STRING,
  last_name                    STRING,
  org_name                     STRING,
  multiple_npi_flag            STRING,
  state_cd                     STRING,
  provider_type_desc           STRING,
  revocation_reason            STRING,
  revocation_effective_date    DATE,
  reenrollment_bar_expiration  DATE,
  _ingestion_timestamp         STRING,
  _batch_id                    STRING
);
